apiVersion: v1
kind: Pod
metadata:
  name: nodeselectorpod
  labels:
    env : test
spec:
  containers:
    - name: nginx
      image: nginx
  tolerations:
    - key: "type"
      operator: "Equal"
      value: "worker1"
