apiVersion: v1
kind: Namespace
metadata:
 name: game-application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
  namespace: game-application
  labels:
    app.kubernetes.io/name: game-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: game-2048
  replicas: 4
  template:
    metadata:
      name: puzzle-game-pod
      labels:
        app.kubernetes.io/name: game-2048
      namespace: game-application
    spec:
      containers:
        - name: 2048-game
          image: alexwhen/docker-2048
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: game-application
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-00098ce8ac67fd6d2"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: game-2048
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
