apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-app
  replicas: 4
  template:
    metadata:
      name: puzzle-game-pod
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-app
      namespace: game-application
    spec:
      containers:
        - name: 2048-game
          image: {{ .Values.server.image}}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.server.port}}
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-security-groups: {{.Values.securityGroup | quote}}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-app
  ports:
    - port: {{ .Values.server.port}}
      targetPort: {{ .Values.server.port}}
      protocol: TCP
