apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: apache
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 2
  template:
    metadata:
      name: apache-pod
      labels:
        app: apache
    spec:
      containers:
        - name: apache-container
          image: httpd
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              port: 80
              path: /index.html
            initialDelaySeconds: 3
            periodSeconds: 4
            timeoutSeconds: 5
            failureThreshold: 4
            successThreshold: 1
