apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    test: liveness
    environment: test
spec:
  containers:
    - name: apache-webserver
      image: httpd    
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 12
