apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    test: liveness
    environment: test
spec:
  containers:
    - name: apache-webserver
      image: httpd
      ports:
        - containerPort: 80
          protocol: TCP
      livenessProbe:
        httpGet:
          port: 80
          path: /index.html
        initialDelaySeconds: 3
        periodSeconds: 4
