apiVersion: v1
kind: Pod
metadata:
  name: multi-containder-pod
spec:

  volumes:
  - name: cache-volume
    emptyDir: {}
    
  containers:
  - image: nginx
    name: nginx-container
    volumeMounts:
    - mountPath: /nginx-cache
      name: cache-volume
  - image: redis
    name: redis-container
    volumeMounts:
      - mountPath: /data/redis
        name: cache-volume
