apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: secret-environment-variable
      image: nginx:latest
      env:
        - name: secret_username
          valueFrom:
            secretKeyRef:
              key: username
              name: test-secret
              optional: false
        - name: secret_password
          valueFrom:
            secretKeyRef:
              key: password
              name: test-secret
              optional: false
